# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 99b3d599f959198eeda292d2e0221c0320633aba710a7ef804622fd17d63fcde0807c925ca07ab4e9c87e91a8751ff15f2d39457b36e2d5d8cefb77f960ca461

test:
  secret_key_base: 81ed6128069f2fb284a73a0dee9f86c285f8099cd31dd17dc23a18844c9edfbd12c867306d7e2bba23ade5d21c600a2aa4584f89b9d5355d504059ee79b6969e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
